// The Homebrew formula for a release, written from its manifest: the prebuilt binary for each platform
// with its SHA-256. The release workflow commits it to manyeya/homebrew-tap.
//   bun .github/scripts/homebrew-formula.ts <manifest.json> <out.rb>
const [manifestPath, out] = Bun.argv.slice(2);
if (!manifestPath || !out) throw new Error("usage: homebrew-formula.ts <manifest.json> <out.rb>");
const m = await Bun.file(manifestPath).json();
const asset = (platform: string) => {
  const a = m.assets[platform];
  if (!a) throw new Error(`the manifest for ${m.version} has no ${platform} build`);
  return `url "${a.url}"\n      sha256 "${a.sha256}"`;
};

await Bun.write(out, `# Generated by .github/scripts/homebrew-formula.ts in manyeya/shepherd for each release.
class Shepherd < Formula
  desc "Agent-aware terminal multiplexer"
  homepage "https://manyeya.github.io/shepherd/"
  version "${m.version}"
  license "MIT"

  on_macos do
    depends_on arch: :arm64
    on_arm do
      ${asset("darwin-arm64")}
    end
  end

  on_linux do
    on_arm do
      ${asset("linux-arm64")}
    end
    on_intel do
      ${asset("linux-x64")}
    end
  end

  def install
    bin.install Dir["shepherd-*"].first => "shepherd"
  end

  test do
    assert_match "shepherd #{version}", shell_output("SHEPHERD_UPDATE_URL=off #{bin}/shepherd --version")
  end
end
`);
console.log(`wrote ${out} for shepherd ${m.version}`);
